name: dart_crud
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Yousoff Effendy <yousoff92@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
 path: ^1.6.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

